### ISSUE TITLE
Autocompletion not works

### ISSUE THREAD

**Issue by AhmetEnesKCC** [bali182/autocomplete-json#113]
Autocompletion at ,prettierrc file does not work.
Also at package.json it is broken too.

it completes the version of dependency but not the name of it.  ( i see your gif has that too )

**Comment by UziTech** [comment]
The package.json dependencies should be fixed in #114.

`.prettierrc` is not supported currently but if you would like to create a provider we could add it. 😁👍

**Comment by AhmetEnesKCC** [comment]
Sounds great. Will try package.json.
It is nice to help you. Work to add it hackable amazing editor :D
