### ISSUE TITLE
Schema Visitor pattern feedback

### ISSUE THREAD

**Issue by bd82** [bali182/autocomplete-json#40]
Hi @bali182.

Continuing our discussion from https://github.com/SAP/chevrotain/issues/135.

I've looked at https://github.com/bali182/autocomplete-json/blob/master/lib/json-schema-visitors.ts

The implementation looks clean and clear. There are a few issues I can raise:

**Major issue:**
It seems like the visitors handle the concern of  traversing the data structure.
```Typescript
visitAnyOfSchema(schema: AnyOfSchema, collector: Array<BaseSchema>): void {
    schema.getSchemas().forEach(childSchema => childSchema.accept(this, collector));
  }
```

This means the visitors need to be aware of internal details of the data structure and not just
performing dispatching by type.
Imagine adding another layer of nesting (composition) in your data structure.
Now **all** the visitors implementations will have to **modified** to accept that nested property as well.
```Typescript
// ALL visitAnyOfSchema will have to modified in ALL visitors if we add a new property that needs be visited.
visitAnyOfSchema(schema: AnyOfSchema, collector: Array<BaseSchema>): void {
    schema.getSchemas().forEach(childSchema => childSchema.accept(this, collector));
    schema.getNewNestedProp().accept(this, collector);  // this change will appear in many visitors
  }
```

A solution for this would be for the accept method on the classes in the data structure to deal with the children.

```Typescript
  accept<P, R>(visitor: ISchemaVisitor<P, R>, parameter: P): R[] {
    let myResult = visitor.visitAnyOfSchema(this, parameter);
    let childrenResults = this.getSchemas().map( (currChild) => currChild.accept(this, parameter);
    return [myResult].concat(childrenResults);
  }
```

This means changes in the data structure won't require changes to the visitors.
The visitors only need to handle the dispatching.

**Comment by bd82** [comment]
**Minor Issue:**
It seems you need to be able to dispatch by the super type.
Specifically dealing with sub classes of CompositeSchema:

In this example you will have to remember to update **ALL** visitors that need a single behavior 
for sub classes of CompositeSchema if a new sub class is created.

```Typescript
visitCompositeSchema(schema: CompositeSchema, request: IRequest) {
    return flatten(schema.getSchemas()
      .filter(s => !(s instanceof AnyOfSchema))
      .map(s => s.accept(this, request).filter(r => r.snippet !== SnippetProposalVisitor.DEFAULT))
    );
  }

  visitAllOfSchema(schema: AllOfSchema, request: IRequest): Array<IProposal> {
    return this.visitCompositeSchema(schema, request);
  }

  visitAnyOfSchema(schema: AnyOfSchema, request: IRequest): Array<IProposal> {
    return this.visitCompositeSchema(schema, request);
  }

  visitOneOfSchema(schema: OneOfSchema, request: IRequest): Array<IProposal> {
    return this.visitCompositeSchema(schema, request);
  }

```

But if you had dispatching by the super class you could write a much simpler:
```Typescript
visitCompositeSchema(schema: CompositeSchema, request: IRequest) {
    return flatten(schema.getSchemas()
      .filter(s => !(s instanceof AnyOfSchema))
      .map(s => s.accept(this, request).filter(r => r.snippet !== SnippetProposalVisitor.DEFAULT))
    );
  }
```

Without any need to update **all** the visitors once the class hierarchy changed.

You can implement this either by instanceof or by traversing the prototype chain.
The prototype approach is what I do [here](https://github.com/SAP/demos_json_editor_services_chevrotain/blob/master/src/pudu/dispatcher.ts#L51)

**Comment by bd82** [comment]
Obviously these issues may not be relevant/serious for a simple class hierarchy especially if you don't expect it to change much. They will matter much more in a large & complex class hierarchy and data structure.

**Comment by bali182** [comment]
Hmm... Thanks for bringing these up. The thing is, I tried to convince you by showing you these examples, that having leaf-class visits is the way to go, but I see your point :smile: . Sure, it would be less code if I had a `visitCompositeSchema()` method in the interface, but that would introduce some ambiguity. Where do I implement accept? In the base class? In each sub classes? If i do it in the base class, how do I know, that the visitor wants to handle all the leaf classes inheriting from the abstract base (`CompositeSchema`) or it just wants to catch all? Maybe do I dispatch to both `visitCompositeSchema()` and `visitXySubtype()` ?

What you noticed about having to change the visitors when something changes in the class hierarchy it visits, was very conscious decision. I would like the compiler to notify me, when I add for example a new `CompositeSchema` subclass, so even if the class hierarchy gets bigger, I'd have to make a conscious decision about how to handle each new class in each visitor.

I guess it's just a difference in how we look at things, I was mostly using statically typed languages, so js is kinda new to me, so maybe I'm trying to force it to do too many things that makes no sense from js perspective.

I looked at the visitor you linked in more detail. It seems like a "reflection" based solution, but it seems very reasonable if you don't know exactly what you will be visiting, and you want something dynamically exploring and calling methods for types in any arbitrary class hierarchy. Also the error which it is thrown in case of a type not handled, makes it as safe as sanely possible. It seems like you also have the problem tackled that I mentioned in the first paragraph (about validating ambiguity). Maybe it's not a problem that the type system should handle? Anyways, I like this solution.

**Comment by bd82** [comment]
```that would introduce some ambiguity. Where do I implement accept? In the base class? In each one of the sub classes? If i do it in the base class, how do I know, that the visitor wants to handle all the leaf classes inheriting from the abstract base```

I'm not 100% sure I understand.
Note that in the standard java implementation of a visitor pattern you do get this behavior of 
implementing a visit for the superclass and having it invoked on subclasses due to the the runtime polymorphic dispatching.

If you extract the polymorphic dispatch logic outside the accept (because there is no such thing in javascript) either using instanceof or prototype investigation.
And you also implement a method called "children()" on all nodes in the hierarchy.
so each node is able to return a collection of its direct children (not subtypes, the actual composed children).

implementing the accept becomes vert simple.

```typescript

class YYY extends BaseNode {

contructor(public childA, public childB){}

children():BaseNode[] {

}

accept(visitor:IVisitor):void {
   visitor.visit(this)
    this.children().map((currChild) => visitor.accept(currChild)
}
}

```

Note that the accept method can even be extracted to the BaseNode class in this case because
it would look the same for all the nodes.


```What you noticed about having to change the visitors when something changes in the class hierarchy it visits, was a very conscious decision.```

:+1:  
In the context of a small hierarchy, a few visitors and a single developer that makes **perfect sense.**
The reflection based visitor I linked to was originally designed in the context of 100+ classes hierarchy, dozens+ of visitors, multiple development teams and does not assume all the teams use typescript (thus includes runtime checks as well).


```I guess it's just a difference in how we look at things, I was mostly using statically typed languages, so js is kinda new to me, so maybe I'm trying to force it to do too many things that makes no sense from js perspective.```

I am also from a statically typed background. nowadays I'm leaning towards a combination of compile time checks + runtime checks + ~100% code coverage to maximize the robustness of the code (and still some bugs manage to sneak by :smile: )

```Also the error which it is thrown in case of a type not handled, makes it as safe as sanely possible.```
Not only will it throw a runtime error if a type is not handled in a specific visitor, it will also throw an error if the baseDispatcher has missing or redundant handlers.
https://github.com/SAP/demos_json_editor_services_chevrotain/blob/master/src/pudu/dispatcher.ts#L162
