### ISSUE TITLE
Autocompletions don't fire for .htmlhintrc.

### ISSUE THREAD

**Issue by rockwalrus** [bali182/autocomplete-json#56]
Schemastore has a [schema for .htmlhintrc files](http://json.schemastore.org/htmlhint), but for some reason, the autocompletions never get triggered, even though the buffer is in JSON mode.

**Comment by bali182** [comment]
I must have removed this for some reason from the readme. autocomplete+ blacklists dotfiles for some reason by default, to enable any kind of autocomplete for them go to `File` -> `Settings` -> `Packages` -> `autocomplete-plus` -> `Settings` -> override default `.*` with something else - a space for example. Let me know if it helps!

**Comment by rockwalrus** [comment]
That was it!
