### ISSUE TITLE
Autocomplete seems broken v5.1.0

### ISSUE THREAD

**Issue by jpolo** [bali182/autocomplete-json#57]
Autocompletion does not autocomplete anything in my package.json

Here is a line that is logged in the console
```
Uncaught (in promise) SyntaxError: Unexpected token ﻿ in JSON at position 0(…) 
```
in node-fetch/body.js

**Comment by bali182** [comment]
Sounds bad, time to load this bad boy again. Thanks for reporting it!

**Comment by bali182** [comment]
Ok, so I could reproduce the error, must have been something with the node-fetch module. I replaced it with axios, and looks like schemas are loading from schemastore properly. Pushed an update: autocomplete-json@v5.2.0 let me know if the issue still persists!

**Comment by jpolo** [comment]
Yes seems to have fixed the problem. Thanks!
