### ISSUE TITLE
npm package.json support broken in Atom

### ISSUE THREAD

**Issue by anandsuresh** [bali182/autocomplete-json#58]
Since the upgrade, when editing package.json files, I no longer receive auto-complete support for package names/versions.

Currently running autocomplete-json v5.1.0 on Atom 1.12.6.

**Comment by anandsuresh** [comment]
Seems 5.2.0 fixed the issue! Closing this now.

**Comment by bali182** [comment]
Ah you were just unlucky  with the timing :) thanks for reporting anyways
