### ISSUE TITLE
Simple fileMatch declaration for custom schema

### ISSUE THREAD

**Issue by kolis** [bali182/autocomplete-json#59]
I think it is a bit excessive to have to declare a service if I have a custom schema (that I don't intend to send to the SchemaStore).

If I have json files with a specific filename pattern it would be very convenient if I could just make a fileMatch declaration in the `package.json`.

A fileMatch pattern + path to the schema file should be enough to enable a custom schema in atom. Or am I missing something?

**Comment by bali182** [comment]
You are absolutely free to do that! Here's how: https://github.com/bali182/autocomplete-json/wiki/SchemaProvider

**Comment by bali182** [comment]
Closing this. Feel free to reopen if my previous answer didn't help!
