### ISSUE TITLE
is there a strict json schema linting mode? 

### ISSUE THREAD

**Issue by wenhoujx** [bali182/autocomplete-json#69]
is there a configuration to validate against the json schema and underline the errors in red? 
for example, i have a package.json where i can add a  ` "optionalDependencies": 123` which violates the json schema for `package.json`. 

if this is out of the scope of this project, would appreciate your recommendations of other package for this purpose, preferably allow custom jsonschema ? 

thanks

**Comment by bali182** [comment]
This package doesn't support schema validation, only autocomplete.

I don't know about / use any package that does this.

If you are planning to create one: 
- https://github.com/steelbrain/linter (it's a generic purpose linter "engine" that you could extend)
- You'll need a schema validator, which reports line/column numbers (I did a bit of research, haven't found one so this is a bit of a challenge)
