### ISSUE TITLE
Not working with cypress.json

### ISSUE THREAD

**Issue by brettz9** [bali182/autocomplete-json#76]
I have a `cypress.json` file, yet despite it being listed at http://schemastore.org/api/json/catalog.json and matching the `fileMatch`, hitting `ctrl-space` (on Mac, Atom 1.40.1), does not open up auto-complete (as it does in say a JavaScript file) (in conjunction with autocomplete-plus).

**Comment by UziTech** [comment]
This should be fixed in the latest release
